Default: &defaults
  host: "127.0.0.1"
  port: 8888
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://konn-san.com/test"
  <<: *defaults
