Default: &defaults
  database: hashdbtest.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: hashdbtest_test.sqlite3
  <<: *defaults

Staging:
  database: hashdbtest_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hashdbtest_production.sqlite3
  poolsize: 100
  <<: *defaults
